### ISSUE TITLE
Сборка HDF4

### ISSUE THREAD

**Issue by alisovenko** [nextgis/ledaps-win-build#1]
Если для сбоки espa-product-formatter использую собранный HDF4 и HDFEOS из ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/ получаю множество undefined reference. Например: undefined reference to `SDsetattr'
В библиотекке  mfhdf.lib существует только '_SDsetattr'

При сборке HDF4 под minGW  с флагом BUILD_SHARED_LIBS получаю ошибку
undefined reference to `_imp__error_top'
хотя в этой сборке hdl.lib содержит '__imp__error_top'

**Comment by simgislab** [comment]
Они вроде бы рекомендуют брать HDF4 и HDF-EOS из другого места:

https://github.com/USGS-EROS/espa-product-formatter

**Comment by simgislab** [comment]
прямая ссылка: ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/HDF-EOS2.19v1.00.tar.Z

по теме (но про убунту): http://karthur.org/2015/ledaps-installation-ubuntu.html

**Comment by simgislab** [comment]
рабочая ссылка на код: http://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/HDF-EOS2.19v1.00.tar.Z

**Comment by BishopGIS** [comment]
Рабочий проект со сборкой всех зависимостей тут: https://github.com/BishopGIS/espa-product-formatter

Тестировалось: 

* Ubuntu 15.10 static build
* Ubuntu 15.10 shared build
* Windows 7 Pro (MSVC 2012 SP5) static build 32bit
* Windows 7 Pro (MSVC 2012 SP5) static build 64bit
* Windows 7 Pro (MSVC 2012 SP5) shared build 32bit
* Windows 7 Pro (MSVC 2012 SP5) shared build 64bit

Для сборки с динамическими библиотеками нужно добавить в cmake-gui ключ *BUILD_SHARED_LIBS* тип BOOL значение ON

Общий алгоритм:

1. Склонировать репозиторий
2. Запустить CMake-GUI и указать путь до папки куда склонирован репозиторий и путь до папки сборки (к пути до папки исходников добавляем build)
3. Нажать Configure. При этом произойдет проверка конфигурации и поиск недостающих зависимостей. Если каких-то обязательных зависимостей не будет то конфигурирование будет прервано с красным диагностическим сообщением.
4. Все зависимости добавляются в группу начинающуюся на *WITH_* - по две штуки - для локальной библиотеки (можно указать путь до заголовочных файлов и собранной библиотеки *.lib) и внешней библиотеки.
5. Если собранной библиотеки нету, то ставим галку как на локальной, так и на внешней библиотеке (оканчивается на *_EXTERNAL*).
6. Повторяем конфигурирование пока не исчезнут все красные строки. Необязательные зависимости тоже подключить (все должно собираться).
7. В CMake-GUI указываем путь до установки (в рамках тестирования я обычно указываю CMAKE_INSTALL_PREFIX в туже папку что и исходники в  подпапку inst).
8. Далее жмем кнопку generate 
9. При сборке в Linux в папке build выполняем make, в Windows открываем файл проекта и запускаем сборку.
10. После удачной сборки выполняем установку - make install или цель INSTALL в MSVC.
11. В папке inst должны быть скопированы: исполняемые файлы и необходимые для запуска библиотеки в папку bin, заголовочные файлы в lib и т.д.

Примечания:

* Сборка будет довольно долгой, так как при указании всех зависимостей получается 13 подпроектов.
